# Generated by Django 5.2 on 2025-05-29 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('total_marks', models.PositiveIntegerField()),
                ('weightage', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='CLO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('taxonomy_level', models.CharField(max_length=50)),
                ('plo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('session', models.CharField(max_length=10)),
                ('semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('clo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluation.clo')),
            ],
        ),
        migrations.CreateModel(
            name='RubricLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_number', models.IntegerField()),
                ('criteria', models.TextField()),
                ('marks', models.PositiveIntegerField()),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluation.rubric')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_marks', models.PositiveIntegerField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluation.assessment')),
                ('rubric_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluation.rubriclevel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluation.student')),
            ],
        ),
    ]
